name: Close preview

on:
  pull_request:
    types: [ closed ]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: check if sample exists
        id: check
        run: |
          git fetch --depth=1
          git checkout gh-pages
          if [[ -d ${{ github.event.number }} ]]; then
            echo "::set-output name=haspg::true"
          else
            echo "::set-output name=haspg::false"
          fi
          git checkout ${{ github.head_ref }}
      - name: checkout to pages
        run: |
          git checkout gh-pages
      - name: Delete pages
        if: steps.check.outputs.haspg == 'true'
        run: |
          rm -r $PR
        env:
          PR: ${{ github.event.number }}

      - name: Commit deleted changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.check.outputs.haspg == 'true'
        with:
          commit_message: Automated Change
          file_pattern: ${{ github.event.number }}
          branch: gh-pages